### ISSUE TITLE
NPM Install Error

### ISSUE THREAD

**Issue by marspu1** [contentful/contentful-export#6] opened 2016-09-20 08:53 UTC
I run from OSX terminal

sudo npm install –g contentful-export

and get

npm ERR! fetch failed https://registry.npmjs.org/contentful-export/-/contentful-export-1.0.6.tgz

npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504

**Comment by Khaledgarbaya** [comment] 2016-09-20 08:59
Hi @marspu1,
Can you provide your npm version  ?
Does your network setup have a proxy ?

**Comment by Khaledgarbaya** [comment] 2016-09-20 09:17
I just tested it and I can confirm that I am getting the same error. That's completely weird.
Can you for now clone the project and do `npm install` and then `npm run build` .
After that you can run `./bin/contentful-export --config myconfig.json`

**Comment by marspu1** [comment] 2016-09-20 09:34
Ah – I installed NPM yesterday. NPM is 2.15.9 – I’ve upgraded to 30.10.7 the install does a dependency check (which it didn’t before and then craps out with the same error. No proxy.

Downloads markspurgen$ sudo npm install -g contentful-export
⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loadAllDepsIntoIdealTree
npm ERR! fetch failed https://registry.npmjs.org/contentful-export/-/contentful-export-1.0.6.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504

Regards, Mark

Mark Spurgen
Co-Founder, Technology & Delivery Director
E: ms@thelifehouse.co<mailto:ms@thelifehouse.co>
M: +44[0] 7796 266533

PRE-REGISTER NOW at: www.thelifehouse.Co

Twitter<https://twitter.com/TheLifehouseCo> |  Facebook<https://www.facebook.com/TheLifehouseCompany> | LinkedIn<https://www.linkedin.com/company/the-lifehouse?trk=company_logo>


The information in this e-mail is strictly confidential and intended solely for the addressee(s). Access to this e-mail by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or action taken or omitted to be taken on it, is prohibited & may be unlawful. Opinions, conclusions and other information expressed in this message are not given or endorsed by the firm or employer unless otherwise indicated by an authorised representative independent of this message.

**Comment by marspu1** [comment] 2016-09-23 06:38
Hi Khaled – I got the JSON extract working thanks. We use the CMS to manage articles with tags. We want to be able to extract a list of the articles and their related fields into a spreadsheet so we can do some analysis  for instance, how many articles are tagged as X which is why I used your code. Unfortunately the JSON output is big and unwieldly. Can I be specific about the Contentful Type or do you have an alternative solution? ☺

Regards, Mark

Mark Spurgen
Co-Founder, Technology & Delivery Director
E: ms@thelifehouse.co<mailto:ms@thelifehouse.co>
M: +44[0] 7796 266533

PRE-REGISTER NOW at: www.thelifehouse.Co

Twitter<https://twitter.com/TheLifehouseCo> |  Facebook<https://www.facebook.com/TheLifehouseCompany> | LinkedIn<https://www.linkedin.com/company/the-lifehouse?trk=company_logo>


The information in this e-mail is strictly confidential and intended solely for the addressee(s). Access to this e-mail by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or action taken or omitted to be taken on it, is prohibited & may be unlawful. Opinions, conclusions and other information expressed in this message are not given or endorsed by the firm or employer unless otherwise indicated by an authorised representative independent of this message.

**Comment by Khaledgarbaya** [comment] 2016-09-23 08:56
Hi @marspu1 ,
the Export tool is intended to get every thing from Contentful using the [sync](https://www.contentful.com/developers/docs/concepts/sync/) api under the hood.
You can achieve easily what you need through our [contentful.js](https://github.com/contentful/contentful.js) and specifying the data that you need as a query.
Here is an example on how to do this.
```javascript
var contentful = require('contentful')
var client = contentful.createClient({
  // This is the space ID. A space is like a project folder in Contentful terms
  space: 'SPACE_ID',
  // This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  accessToken: 'DELIVERY_ACCESS_TOKEN'
})

// Get me all entries based on this contentType
await client.getEntries({content_type:'CONTENT_TYPE_ID', 'fields.tag.sys.id':'tagid'})
```

This way you will get only what you need as a response, since our SDK in Compatible with nodejs target also you can save the output to file system and with some tweaks you can output in the format that you want.

I hope that helps you, if you have anymore questions feel free to ping me 

Best,
Khaled

**Comment by marspu1** [comment] 2016-09-23 09:29
Brilliant – I’ll give it a go!


Mark Spurgen
Co-Founder, Technology & Delivery Director
E: ms@thelifehouse.co<mailto:ms@thelifehouse.co>
M: +44[0] 7796 266533

PRE-REGISTER NOW at: www.thelifehouse.Co

Twitter<https://twitter.com/TheLifehouseCo> |  Facebook<https://www.facebook.com/TheLifehouseCompany> | LinkedIn<https://www.linkedin.com/company/the-lifehouse?trk=company_logo>


The information in this e-mail is strictly confidential and intended solely for the addressee(s). Access to this e-mail by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or action taken or omitted to be taken on it, is prohibited & may be unlawful. Opinions, conclusions and other information expressed in this message are not given or endorsed by the firm or employer unless otherwise indicated by an authorised representative independent of this message.

**Comment by Khaledgarbaya** [comment] 2016-09-23 09:40
Hi @marspu1 ,
I will close this issue for now, feel free to create a new one when you have questions

Best,
Khaled

**Closed by Khaledgarbaya** 2016-09-23 09:40 UTC
